### ISSUE TITLE
GameConsole only works with your game

### ISSUE THREAD

**Issue by bokherus** [OOP2018/guessing-game-KorawitRupanya#1]
It should play a NumberGame so that the console could run any game that extends the NumberGame.

https://github.com/OOP2018/guessing-game-KorawitRupanya/blob/d7c04d29148cdc67a0978b08eb0c9c520554152d/src/GameConsole.java#L11

**Comment by KorawitRupanya** [comment]
I change that line in to this "public int play(NumberGame game) { " and it still run so is it right?

**Comment by bokherus** [comment]
Your game "KorawitGame" extends from NumberGame, so it's considered as a kind of NumberGame so it is right. I hope you understand the reason why it works. Anyway, well done
