### ISSUE TITLE
Please don't use while (true)

### ISSUE THREAD

**Issue by bokherus** [OOP2018/guessing-game-KorawitRupanya#2]
You could use boolean result from `guess(number)` to determine whether the loop should continue running.

https://github.com/OOP2018/guessing-game-KorawitRupanya/blob/d7c04d29148cdc67a0978b08eb0c9c520554152d/src/GameSolver.java#L17-L32

**Comment by KorawitRupanya** [comment]
I don't understand this is the GameSolver class so where is the result from that boolean come form because that result is happen only when user guess a number.

**Comment by KorawitRupanya** [comment]
OK. I get it thank you for the issue.
